AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example SAM template for GitHub Lambda Deployer

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 256

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Description: Example Lambda function deployed via GitHub Lambda Deployer
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Tags:
        DeployedBy: GitHubLambdaDeployer

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'

  HelloWorldFunction:
    Description: Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: IAM Role for Lambda Function
    Value: !GetAtt HelloWorldFunctionRole.Arn
